"""Add business models and update application

Revision ID: 19f2fb7427ca
Revises: 0b0f0b4f56d0
Create Date: 2026-09-24 23:27:08.642350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f2fb7427ca'
down_revision: Union[str, Sequence[str], None] = '0b0f0b4f56d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factory_units',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.Column('midc_plot_number', sa.String(), nullable=True),
    sa.Column('location_district', sa.String(), nullable=False),
    sa.Column('investment_amount', sa.Integer(), nullable=True),
    sa.Column('employment_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factory_units_id'), 'factory_units', ['id'], unique=False)
    op.add_column('applications', sa.Column('business_id', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('assigned_officer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'applications', 'users', ['assigned_officer_id'], ['id'])
    op.create_foreign_key(None, 'applications', 'business_profiles', ['business_id'], ['id'])
    op.add_column('business_profiles', sa.Column('cin_number', sa.String(), nullable=True))
    op.add_column('business_profiles', sa.Column('industry_sector', sa.String(), nullable=False))
    op.add_column('business_profiles', sa.Column('registration_type', sa.String(), nullable=False))
    op.add_column('business_profiles', sa.Column('address', sa.String(), nullable=True))
    op.alter_column('business_profiles', 'pan_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_business_profiles_gstin'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_pan_number'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_user_id'), table_name='business_profiles')
    op.create_unique_constraint(None, 'business_profiles', ['user_id'])
    op.create_unique_constraint(None, 'business_profiles', ['pan_number'])
    op.drop_column('business_profiles', 'investment_value')
    op.drop_column('business_profiles', 'employment_count')
    op.drop_column('business_profiles', 'designation')
    op.drop_column('business_profiles', 'industry')
    op.drop_column('business_profiles', 'gstin')
    op.drop_column('business_profiles', 'district')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('business_profiles', sa.Column('gstin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('business_profiles', sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('business_profiles', sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('business_profiles', sa.Column('employment_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('business_profiles', sa.Column('investment_value', sa.VARCHAR(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'business_profiles', type_='unique')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'business_profiles', type_='unique')
    op.create_index(op.f('ix_business_profiles_user_id'), 'business_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_business_profiles_pan_number'), 'business_profiles', ['pan_number'], unique=True)
    op.create_index(op.f('ix_business_profiles_gstin'), 'business_profiles', ['gstin'], unique=True)
    op.alter_column('business_profiles', 'pan_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('business_profiles', 'address')
    op.drop_column('business_profiles', 'registration_type')
    op.drop_column('business_profiles', 'industry_sector')
    op.drop_column('business_profiles', 'cin_number')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'applications', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'assigned_officer_id')
    op.drop_column('applications', 'business_id')
    op.drop_index(op.f('ix_factory_units_id'), table_name='factory_units')
    op.drop_table('factory_units')
    # ### end Alembic commands ###
