"""add caf models

Revision ID: 38fa5e9bb616
Revises: b8a2f6c18c03
Create Date: 2026-09-24 00:48:26.770135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38fa5e9bb616'
down_revision: Union[str, Sequence[str], None] = 'b8a2f6c18c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caf_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wizard_run_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wizard_run_id'], ['wizard_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caf_forms_id'), 'caf_forms', ['id'], unique=False)
    op.create_table('caf_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caf_form_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caf_form_id'], ['caf_forms.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caf_services_id'), 'caf_services', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_caf_services_id'), table_name='caf_services')
    op.drop_table('caf_services')
    op.drop_index(op.f('ix_caf_forms_id'), table_name='caf_forms')
    op.drop_table('caf_forms')
    # ### end Alembic commands ###
