"""Update applications table and add payments

Revision ID: 4385b78e4578
Revises: 1f472f0a7704
Create Date: 2026-09-23 23:50:46.563192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4385b78e4578'
down_revision: Union[str, Sequence[str], None] = '1f472f0a7704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_application_id'), 'payments', ['application_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_reference_id'), 'payments', ['reference_id'], unique=True)
    op.add_column('applications', sa.Column('business_profile_id', sa.Integer(), nullable=False))
    op.add_column('applications', sa.Column('factory_unit_id', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('service_id', sa.Integer(), nullable=False))
    op.add_column('applications', sa.Column('current_stage_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_applications_business_profile_id'), 'applications', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_applications_factory_unit_id'), 'applications', ['factory_unit_id'], unique=False)
    op.create_index(op.f('ix_applications_service_id'), 'applications', ['service_id'], unique=False)
    op.create_foreign_key(None, 'applications', 'factory_units', ['factory_unit_id'], ['id'])
    op.create_foreign_key(None, 'applications', 'business_profiles', ['business_profile_id'], ['id'])
    op.create_foreign_key(None, 'applications', 'tracking_stages', ['current_stage_id'], ['id'])
    op.create_foreign_key(None, 'applications', 'services', ['service_id'], ['id'])
    op.drop_column('applications', 'service_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_service_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_factory_unit_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_business_profile_id'), table_name='applications')
    op.drop_column('applications', 'current_stage_id')
    op.drop_column('applications', 'service_id')
    op.drop_column('applications', 'factory_unit_id')
    op.drop_column('applications', 'business_profile_id')
    op.drop_index(op.f('ix_payments_reference_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_application_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
