"""update factory units

Revision ID: 511c0e2ebd02
Revises: 63861b307d08
Create Date: 2026-09-26 16:21:37.357026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511c0e2ebd02'
down_revision: Union[str, Sequence[str], None] = '63861b307d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factory_units', sa.Column('category', sa.String(), nullable=True))
    op.add_column('factory_units', sa.Column('operational_status', sa.String(), nullable=True))
    op.add_column('factory_units', sa.Column('midc_area', sa.String(), nullable=True))
    op.add_column('factory_units', sa.Column('taluka', sa.String(), nullable=True))
    op.add_column('factory_units', sa.Column('district', sa.String(), nullable=True))
    op.add_column('factory_units', sa.Column('plot_number', sa.String(), nullable=True))
    op.add_column('factory_units', sa.Column('survey_number', sa.String(), nullable=True))
    op.add_column('factory_units', sa.Column('power_sanctioned_kva', sa.Integer(), nullable=True))
    op.add_column('factory_units', sa.Column('water_demand_kl', sa.Integer(), nullable=True))
    op.add_column('factory_units', sa.Column('built_up_area_sqm', sa.Integer(), nullable=True))
    op.drop_column('factory_units', 'midc_plot_number')
    op.drop_column('factory_units', 'location_district')
    op.drop_column('factory_units', 'investment_amount')
    op.drop_column('factory_units', 'employment_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factory_units', sa.Column('employment_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('factory_units', sa.Column('investment_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('factory_units', sa.Column('location_district', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('factory_units', sa.Column('midc_plot_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('factory_units', 'built_up_area_sqm')
    op.drop_column('factory_units', 'water_demand_kl')
    op.drop_column('factory_units', 'power_sanctioned_kva')
    op.drop_column('factory_units', 'survey_number')
    op.drop_column('factory_units', 'plot_number')
    op.drop_column('factory_units', 'district')
    op.drop_column('factory_units', 'taluka')
    op.drop_column('factory_units', 'midc_area')
    op.drop_column('factory_units', 'operational_status')
    op.drop_column('factory_units', 'category')
    # ### end Alembic commands ###
