"""Add code to services

Revision ID: 552884b0e73b
Revises: 38fa5e9bb616
Create Date: 2026-09-24 02:18:00.538210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552884b0e73b'
down_revision: Union[str, Sequence[str], None] = '38fa5e9bb616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('code', sa.String(), nullable=True))
    op.create_index(op.f('ix_services_code'), 'services', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_code'), table_name='services')
    op.drop_column('services', 'code')
    # ### end Alembic commands ###
