"""Add gstin and doi to business profile

Revision ID: a3605cd0422a
Revises: 511c0e2ebd02
Create Date: 2026-09-27 20:36:13.342519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3605cd0422a'
down_revision: Union[str, Sequence[str], None] = '511c0e2ebd02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('gstin', sa.String(), nullable=True))
    op.add_column('business_profiles', sa.Column('date_of_incorporation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'date_of_incorporation')
    op.drop_column('business_profiles', 'gstin')
    # ### end Alembic commands ###
