"""add wizard models

Revision ID: b8a2f6c18c03
Revises: 4385b78e4578
Create Date: 2026-09-24 00:42:39.649370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a2f6c18c03'
down_revision: Union[str, Sequence[str], None] = '4385b78e4578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wizard_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wizard_runs_id'), 'wizard_runs', ['id'], unique=False)
    op.create_table('wizard_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wizard_run_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['wizard_run_id'], ['wizard_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wizard_run_id')
    )
    op.create_index(op.f('ix_wizard_results_id'), 'wizard_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wizard_results_id'), table_name='wizard_results')
    op.drop_table('wizard_results')
    op.drop_index(op.f('ix_wizard_runs_id'), table_name='wizard_runs')
    op.drop_table('wizard_runs')
    # ### end Alembic commands ###
