"""Add factory_units and midc_plots tables

Revision ID: c9b9fbcddf62
Revises: d6bfbd19cd3f
Create Date: 2026-09-23 23:23:58.666590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b9fbcddf62'
down_revision: Union[str, Sequence[str], None] = 'd6bfbd19cd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factory_units',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_profile_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('power_sanctioned_kva', sa.Float(), nullable=True),
    sa.Column('water_demand_kl', sa.Float(), nullable=True),
    sa.Column('built_up_area_sqm', sa.Float(), nullable=True),
    sa.Column('operational_status', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factory_units_business_profile_id'), 'factory_units', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_factory_units_id'), 'factory_units', ['id'], unique=False)
    op.create_index(op.f('ix_factory_units_user_id'), 'factory_units', ['user_id'], unique=False)
    op.create_table('midc_plots',
    sa.Column('factory_unit_id', sa.Integer(), nullable=False),
    sa.Column('midc_area', sa.String(), nullable=True),
    sa.Column('plot_number', sa.String(), nullable=True),
    sa.Column('survey_number', sa.String(), nullable=True),
    sa.Column('taluka', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['factory_unit_id'], ['factory_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_midc_plots_factory_unit_id'), 'midc_plots', ['factory_unit_id'], unique=True)
    op.create_index(op.f('ix_midc_plots_id'), 'midc_plots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_midc_plots_id'), table_name='midc_plots')
    op.drop_index(op.f('ix_midc_plots_factory_unit_id'), table_name='midc_plots')
    op.drop_table('midc_plots')
    op.drop_index(op.f('ix_factory_units_user_id'), table_name='factory_units')
    op.drop_index(op.f('ix_factory_units_id'), table_name='factory_units')
    op.drop_index(op.f('ix_factory_units_business_profile_id'), table_name='factory_units')
    op.drop_table('factory_units')
    # ### end Alembic commands ###
