"""add created_at to business_profile

Revision ID: e113ea3702ee
Revises: a3605cd0422a
Create Date: 2026-09-28 00:50:55.843607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e113ea3702ee'
down_revision: Union[str, Sequence[str], None] = 'a3605cd0422a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('business_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('business_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_business_profiles_id'), 'business_profiles', ['id'], unique=False)
    op.drop_constraint('business_profiles_user_id_fkey', 'business_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'business_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'business_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('business_profiles_user_id_fkey'), 'business_profiles', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_business_profiles_id'), table_name='business_profiles')
    op.alter_column('business_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('business_profiles', 'updated_at')
    op.drop_column('business_profiles', 'created_at')
    # ### end Alembic commands ###
